services:
  db:
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    container_name: db_container
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db:
