services:
  db:
    image: mariadb:10.6.2
    container_name: db_container
    environment:
      - MYSQL_DATABASE=flask_app
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysqldb:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
